import './main.js/fetch-pokemon';
import './main.js/render-api';
import './main.js/logo-animation';
import './main.js/search-btn';
import './main.js/reset-input';
import './main.js/btn-theme';
import './main.js/paralax.min';
import './main.js/body-paralax';
import './main.js/full-collection-api';
